### ISSUE TITLE
Server not stopping with correct signals

### ISSUE THREAD

**Issue by ghost** [resgateio/resgate#35] opened 2018-07-22 06:20 UTC
I setup resgate to run in tandem with some other processes as part of my setup.

Using go-cmd, and raised an issue here:

https://github.com/go-cmd/cmd/issues/19#issuecomment-406827169

The test code to reproduce I don't have accessible but the 20 line example code in go-cmd is the same and so very easy to try.

It is important that spawned servers inside NATS terminate correctly in order for them to be well managed by the process manager.
I have not tried resgate with systemd or launchd or windows service yet.
I intend to try that next

**Comment by jirenius** [comment] 2018-07-24 07:40
Great that you try these things. Thanks!

Stopping of resgate can be initiated in two ways:  
[By signal](https://github.com/jirenius/resgate/blob/master/main.go#L179) (os.Interrupt, os.Kill, syscall.SIGHUP, syscall.SIGTERM, or syscall.SIGQUIT)  
Or by [resgate internally deciding to stop](https://github.com/jirenius/resgate/blob/master/main.go#L188), which happens if:

* [It fails to start the webserver](https://github.com/jirenius/resgate/blob/master/service/httpServer.go#L35) (maybe I should change resgate to wait with returning from Start until it ensures the webserver was correctly started).
* [NATS connection is lost](https://github.com/jirenius/resgate/blob/master/service/mqClient.go#L46)

In any of these cases, resgate will try to do a graceful shutdown for 10 seconds, after which it will exit with a panic (to provide a stacktrace as of why it failed to shut down):  
https://github.com/jirenius/resgate/blob/master/main.go#L202

That means, resgate should *always* exit within 10 seconds after receiving a signal.

But it might exit without calling `os,Exit`, or it might exit with a `panic`.

What sort of termination is required by go-cmd (or any of the other wrappers, for that matter)?

I will try to reproduce the issue as well.

**Comment by gedw99** [comment] 2018-07-24 07:51
The last question about what sort of termination.. I don't know to be frank.
The source for go-cmd is pretty lean so maybe worth looking at.

Or maybe solve the problem. The only reason I raised this is to enable Devs
and end users to easily add Microservice on the same box or a set of boxes
and just have everything work and die and log to one place.
In other words frictionless deployment with docker or K8 !

Hashicorp nomad is a pretty good option that I got working running
resgate,. Go-res and node from a single command.
It updates the whole deployment whenever the source is committed.

So it sort off comes down to deciding if nomad is the approach or something
like go-cmd.
I favour nomad, consul, vault. Together they give the big boy enterprise
stuff everyone needs without needing docker or K8.
If you want to use docker and K8 nomad supports that too btw.

I can finish my setup and upload it.
But we should decide this because they are tied to other issues. Like
security and if vault is used.

Or we can leave it alone too and just use small bits of code to accomplish
deployment and updates.

Curious what your own objectives here are.

**Comment by jirenius** [comment] 2019-08-05 12:10
I've investigated the exit codes returned by Resgate.

Resgate does respond to the Interrupt signal, as expected, exiting with code 0 on successful shutdown.
In other cases, such as disconnects from NATS server, Resgate correctly exits with error code 1.

I’m closing this issue because it has been inactive for a few months, and without being able to reproduce the issue.

**Closed by jirenius** 2019-08-05 12:10 UTC
Labels: bug
